# PVC untuk logs sws-apiadapter
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-sws-apiadapter-pvc
  namespace: sws-kube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

---
# Deployment service sws-apiadapter
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sws-apiadapter
  namespace: sws-kube
  labels:
    app: sws-apiadapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sws-apiadapter
  template:
    metadata:
      labels:
        app: sws-apiadapter
    spec:
      hostname: sws-apiadapter
      securityContext:
        fsGroup: 185
      containers:
        - name: sws-apiadapter
          image: eastnetsdemo/apiadapter:5.1.9-oracle
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 185
          ports:
            - containerPort: 8401
          volumeMounts:
            # - name: config-volume
            #   mountPath: /home/jboss/config/application.properties
            #   subPath: application.properties
            - name: log-volume
              mountPath: /home/jboss/logs
          env:
            - name: TZ
              value: "Asia/Jakarta"
            - name: EASTNETS_CONFIG_HOME
              value: "/etc"
            # - name: JAVA_TOOL_OPTIONS
            #   value: "-XX:MaxRAMPercentage=90"
            - name: ZK_CONNECT_STRING
              value: "zookeeper-headless.sws-fels.svc.cluster.local:2181"
            - name: JAVA_TOOL_OPTIONS
              value: >
                -XX:MaxRAMPercentage=90
                -XX:MaxRAMPercentage=90
                -Xmx1g
                -DlistenerPort=8401
                -DzkConnectString=zookeeper-headless.sws-fels.svc.cluster.local:2181
                -DisLegacyHttpFactory=true
            - name: JAVA_OPTS
              value: >
                -Xmx1g
                -DlistenerPort=8401
                -DzkConnectString=zookeeper-headless.sws-fels.svc.cluster.local:2181
                -DisLegacyHttpFactory=true
          resources:
            limits:
              memory: "1024Mi"
            requests:
              memory: "512Mi"
          livenessProbe:
            tcpSocket:
              port: 8401
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 8401
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        # - name: config-volume
        #   configMap:
        #     name: sws-srvc-config
        - name: log-volume
          persistentVolumeClaim:
            claimName: logs-sws-apiadapter-pvc

---
# Service untuk sws-apiadapter
apiVersion: v1
kind: Service
metadata:
  name: sws-apiadapter
  namespace: sws-kube
spec:
  selector:
    app: sws-apiadapter
  ports:
    - protocol: TCP
      port: 8401         # <-- port yang digunakan untuk akses dari luar (ClusterIP/NodePort/Ingress)
      targetPort: 8401   # <-- port sebenarnya di dalam container
  type: ClusterIP
