apiVersion: v1
kind: ConfigMap
metadata:
  name: sws-srvc-config
  namespace: sws-kube
data:
  application.properties: |
    zookeeper.connect-string=zookeeper-headless.sws-kube.svc.cluster.local:2181
    kafka.bootstrap.servers=kafka-headless.sws-kube.svc.cluster.local:9092
    %oracle.database.jdbc.scdb.url=jdbc:oracle:thin:@192.168.220.70:1521/safewatch
    %oracle.database.jdbc.filtering.url=jdbc:oracle:thin:@192.168.220.70:1521/safewatch
    %oracle.quarkus.datasource."scdbPU".username=scdb
    %oracle.quarkus.datasource."scdbPU".password=47d65070cc33c31965ab8b61faf8078c
    %oracle.quarkus.datasource."filteringPU".username=swserver
    %oracle.quarkus.datasource."filteringPU".password=47d65070cc33c31965ab8b61faf8078c
    quarkus.log.file.enable=true
    quarkus.http.port=8180
    %oracle.database.db-kind=oracle
    %oracle.quarkus.hibernate-orm."filteringPU".log.sql=false
    %oracle.quarkus.hibernate-orm."scdbPU".log.sql=false