---
apiVersion: v1
kind: Namespace
metadata:
  name: sws-kube

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-sws-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/log/swf
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-sws-pvc
  namespace: sws-kube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: logs-sws-pv

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sws-srvc-license-config
  namespace: sws-kube
data:
  application.properties: |
    zookeeper.connect-string=zookeeper-headless.sws-kube.svc.cluster.local:2181
    kafka.bootstrap.servers=kafka-headless.sws-kube.svc.cluster.local:9092
    %oracle.database.jdbc.scdb.url=jdbc:oracle:thin:@192.168.220.70:1521/safewatch
    %oracle.database.jdbc.filtering.url=jdbc:oracle:thin:@192.168.220.70:1521/safewatch
    %oracle.quarkus.datasource."scdbPU".username=scdb
    %oracle.quarkus.datasource."scdbPU".password=47d65070cc33c31965ab8b61faf8078c
    %oracle.quarkus.datasource."filteringPU".username=swserver
    %oracle.quarkus.datasource."filteringPU".password=47d65070cc33c31965ab8b61faf8078c
    quarkus.log.file.enable=true
    %oracle.database.db-kind=oracle
    %oracle.quarkus.hibernate-orm."filteringPU".log.sql=true
    %oracle.quarkus.hibernate-orm."scdbPU".log.sql=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sws-srvc-license
  namespace: sws-kube
  labels:
    app: sws-srvc-license
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sws-srvc-license
  template:
    metadata:
      labels:
        app: sws-srvc-license
    spec:
      hostname: sws-srvc-license
      containers:
        - name: sws-srvc-license
          image: eastnetsdemo/srvc-license:5.1.9-oracle
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8180
          volumeMounts:
            - name: config-volume
              mountPath: /home/jboss/config/application.properties
              subPath: application.properties
            - name: log-volume
              mountPath: /home/jboss/logs
          env:
            - name: TZ
              value: "Asia/Jakarta"
            - name: EASTNETS_CONFIG_HOME
              value: "/etc"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=90"
          #  - name: QUARKUS_LOG_LEVEL
          #    value: DEBUG
            - name: QUARKUS_CONFIG_LOCATION
              value: /home/jboss/config/application.properties
          resources:
            limits:
              memory: "1024Mi"
            requests:
              memory: "512Mi"
          livenessProbe:
            tcpSocket:
              port: 8180
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 8180
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: config-volume
          configMap:
            name: sws-srvc-license-config
        - name: log-volume
          persistentVolumeClaim:
            claimName: logs-sws-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: sws-srvc-license
  namespace: sws-kube
spec:
  selector:
    app: sws-srvc-license
  ports:
    - protocol: TCP
      port: 8180
      targetPort: 8180
  type: ClusterIP
