apiVersion: v1
kind: Service
metadata:
  name: sws-srvc-archive
  namespace: sws-kube
spec:
  selector:
    app: sws-srvc-archive
  ports:
    - protocol: TCP
      port: 8180        # port yang akan diakses pod lain di cluster
      targetPort: 8180  # port di dalam container
  type: ClusterIP