apiVersion: apps/v1
kind: Deployment
metadata:
  name: sws-srvc-scan-persistence
  namespace: sws-kube
  labels:
    app: sws-srvc-scan-persistence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sws-srvc-scan-persistence
  template:
    metadata:
      labels:
        app: sws-srvc-scan-persistence
    spec:
      hostname: sws-srvc-scan-persistence
      securityContext:
        fsGroup: 185
      containers:
        - name: sws-srvc-scan-persistence
          image: eastnetsdemo/srvc-scan-persistence:5.1.9-oracle
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 185
          ports:
            - containerPort: 8180
          volumeMounts:
            - name: config-volume
              mountPath: /home/jboss/config/application.properties
              subPath: application.properties  
            - name: log-volume
              mountPath: /home/jboss/logs
          env:
            - name: TZ
              value: "Asia/Jakarta"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=90"
          resources:
            limits:
              memory: "1024Mi"
            requests:
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8180
              scheme: HTTP
            initialDelaySeconds: 50
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8180
              scheme: HTTP
            initialDelaySeconds: 50
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
      volumes:
        - name: config-volume
          configMap:
            name: sws-srvc-config
        - name: log-volume
          persistentVolumeClaim:
            claimName: logs-sws-scan-persistence-pvc