apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-sws-scan-persistence-pvc
  namespace: sws-kube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn