apiVersion: v1
kind: Service
metadata:
  name: sws-srvc-scan-persistence
  namespace: sws-kube
spec:
  selector:
    app: sws-srvc-scan-persistence
  ports:
    - protocol: TCP
      port: 8180        # port untuk akses antar pod
      targetPort: 8180  # port internal container
  type: ClusterIP