apiVersion: v1
kind: Service
metadata:
  name: sws-srvc-user
  namespace: sws-kube
spec:
  selector:
    app: sws-srvc-user
  ports:
    - protocol: TCP
      port: 8180        # port yang digunakan pod lain untuk akses
      targetPort: 8180  # port di dalam container
  type: ClusterIP