apiVersion: v1
kind: Service
metadata:
  name: sws-srvc-list
  namespace: sws-kube
spec:
  selector:
    app: sws-srvc-list
  ports:
    - protocol: TCP
      port: 8180        # <-- port yang digunakan untuk akses dari luar (ClusterIP/NodePort/Ingress)
      targetPort: 8180  # <-- port sebenarnya di dalam container
  type: ClusterIP